添加云养猫插件
FloatTech/ZeroBot-Plugin-Playground pull request #121
Opened 2023-02-17 16:07 UTC by fangliuyu

2023-02-17 16:21 UTC, Jiang-Red commented on plugin/cybercat/catdata.go
> +	err = sql.db.FindFor(gid, &info, "group by Weight", func() error {
这里可以直接order by xxx desc就不用sort了

2023-02-17 16:22 UTC, Jiang-Red commented on plugin/cybercat/arena.go
> +		if wallet.InsertWalletOf(winer.User, money) == nil {
不输出err的话可以加个文案比如`本次比赛没有奖金`

2023-02-17 16:33 UTC, Jiang-Red requested changes

2023-02-17 16:33 UTC, Jiang-Red commented on plugin/cybercat/store.go
> +			messageText = "你前往的喵喵店时发现正好有活动,\n一袋猫粮现在只需要" + strconv.Itoa(foodmoney) + ";\n"
合并

2023-02-18 00:23 UTC, fangliuyu commented on plugin/cybercat/store.go
> +			messageText = "你前往的喵喵店时发现正好有活动,\n一袋猫粮现在只需要" + strconv.Itoa(foodmoney) + ";\n"
这个不是本就是合并了吗。。。

2023-02-18 10:18 UTC, Jiang-Red commented on plugin/cybercat/store.go
> +			messageText = "你前往的喵喵店时发现正好有活动,\n一袋猫粮现在只需要" + strconv.Itoa(foodmoney) + ";\n"
草。目害了

2023-02-18 10:34 UTC, Jiang-Red requested changes

2023-02-18 10:34 UTC, Jiang-Red commented on plugin/cybercat/arena.go
> +		duelID, _ := strconv.ParseInt(duelStr, 10, 64)
float/math里有个math.Str2Int64

2023-02-18 10:34 UTC, Jiang-Red commented on plugin/cybercat/catdata.go
> +func (s catDataList) Len() int {
是我目害了吗。这几个在哪用到了

2023-02-18 10:34 UTC, Jiang-Red commented on plugin/cybercat/catdata.go
> +	data, _ := web.GetData("https://api.thecatapi.com/v1/images/search?has_breeds=1")
链接都放到const，下面的也是
不用err做检查是有什么深意吗，不是很懂

2023-02-18 16:13 UTC, Jiang-Red approved these changes

2023-02-18 16:13 UTC, merged