FGO相关插件
FloatTech/ZeroBot-Plugin-Playground pull request #151
Opened 2023-03-24 09:45 UTC by rootwlmX

2023-03-24 16:39 UTC, Jiang-Red requested changes
修lint, 然后gormv1换用gormv2

2023-03-24 16:39 UTC, Jiang-Red commented on plugin/fgopickup/handler.go
> +	msg := message.Message{}
```go
msg := make(message.Message,len(pickups))
for i,pickup := range pickups {
    msg[i]=ctxext.FakeSenderForwardNoed(ctx,...)
}
```

2023-03-24 16:39 UTC, Jiang-Red commented on plugin/fgopickup/handler.go
> +		name := message.Text("\n" + pickup.Name)
无需+号，直接, 分割就行

2023-03-24 16:39 UTC, Jiang-Red commented on plugin/fgopickup/handler.go
> +func pickupDetail(ctx *zero.Ctx) {
这写了个什么

2023-03-27 03:26 UTC, rootwlmX commented on plugin/fgopickup/handler.go
> +func pickupDetail(ctx *zero.Ctx) {
试了下前缀匹配到的参数，后面会写上这功能

2023-03-28 14:36 UTC, Jiang-Red requested changes

2023-03-28 14:36 UTC, Jiang-Red commented on plugin/fgopickup/dbengine.go
> +			err := f.Close()
无需判断err
直接
```go
defer f.Close()

2023-03-28 14:36 UTC, Jiang-Red commented on plugin/fgopickup/handler.go
> +func handleError(ctx *zero.Ctx) {
没必要的封装

2023-03-28 14:36 UTC, Jiang-Red commented on plugin/fgopickup/dao.go
> +type dao struct {
没用过gorm
但应该要加锁
下面这样可以直接dao.Lock()
```
type dao struct {
    sync.Mutex
    DBEngine *orm
}

2023-03-28 14:36 UTC, Jiang-Red commented on plugin/fgopickup/dao.go
> +		logrus.Debugln(err)
有错误统一到调用处处理，无需打印，下同

2023-03-28 14:36 UTC, Jiang-Red commented on plugin/fgopickup/handler.go
> +func getMsgOfSinglePickup(ctx *zero.Ctx, pickup pickup) message.MessageSegment {
不要返回message.MessageSegment

2023-03-28 14:36 UTC, Jiang-Red commented on plugin/fgopickup/handler.go
> +	if err != nil {
无意义的err判断，有错会自动为0

2023-03-28 14:36 UTC, Jiang-Red commented on plugin/fgopickup/main.go
> +		Banner:            "https://wx2.sinaimg.cn/large/0083LFbYgy1hcfkreklmbj31e012w7i5.jpg",
这个链接确定可以？我无法访问。
并且看起来像是新浪的链接，新浪的图床反爬，需要加referer才能访问，这样不行

2023-03-28 14:36 UTC, Jiang-Red commented on plugin/fgopickup/handler.go
> +	msg[2] = ctxext.FakeSenderForwardNode(ctx, message.Text("以下为UP从者"))
可以和上面合并

2023-03-29 07:45 UTC, rootwlmX commented on plugin/fgopickup/main.go
> +		Banner:            "https://wx2.sinaimg.cn/large/0083LFbYgy1hcfkreklmbj31e012w7i5.jpg",
直接访问确实不行，但是发图片使用链接可以发出来

2023-03-29 07:47 UTC, rootwlmX commented on plugin/fgopickup/handler.go
> +	msg[2] = ctxext.FakeSenderForwardNode(ctx, message.Text("以下为UP从者"))
是这个意思吗
`ctxext.FakeSenderForwardNode(ctx, message.Text("距今还有", days, "天","以下为UP从者"))`

2023-03-29 07:49 UTC, rootwlmX commented on plugin/fgopickup/main.go
> +		Banner:            "https://wx2.sinaimg.cn/large/0083LFbYgy1hcfkreklmbj31e012w7i5.jpg",
> 这个链接确定可以？我无法访问。 并且看起来像是新浪的链接，新浪的图床反爬，需要加referer才能访问，这样不行

直接访问确实不行，但是发图片使用链接可以发出来

2023-03-29 07:49 UTC, rootwlmX commented on plugin/fgopickup/handler.go
> +	msg[2] = ctxext.FakeSenderForwardNode(ctx, message.Text("以下为UP从者"))
> 可以和上面合并

是这个意思吗
`ctxext.FakeSenderForwardNode(ctx, message.Text("距今还有", days, "天","以下为UP从者"))`

2023-03-29 08:15 UTC, Jiang-Red commented on plugin/fgopickup/handler.go
> +func getMsgOfSinglePickup(ctx *zero.Ctx, pickup pickup) message.MessageSegment {
在调用处再ctxext.FakeSenderForwardNode(...)
```go
return message.Message{banner,id,name,date}
```

2023-03-29 11:33 UTC, Jiang-Red requested changes

2023-03-29 11:33 UTC, Jiang-Red commented on plugin/fgopickup/handler.go
> +		ctx.Send("查询出错！")
输出一下详细错误
```go
ctx.SendChain(message.Text("ERROR: ", err, "解释: 查询出错！"))

2023-03-29 11:33 UTC, Jiang-Red commented on plugin/fgopickup/dao.go
> +type dao struct {
去看了下其他人gorm怎么写的，发现是不用加锁的，不好意思

2023-03-30 08:48 UTC, Jiang-Red approved these changes

2023-03-30 08:48 UTC, merged