fix cahtgpt无法取消授权的问题
FloatTech/ZeroBot-Plugin-Playground pull request #220
Opened 2023-05-26 11:56 UTC by lianhong2758

2023-05-29 14:45 UTC, Jiang-Red approved these changes

2023-05-29 14:49 UTC, Jiang-Red requested changes

2023-05-29 14:49 UTC, Jiang-Red commented on plugin/klala/klala.go
> +		for i := 0; i < 4; i++ {
为什么不for range?

2023-05-29 14:49 UTC, Jiang-Red commented on plugin/klala/klala.go
> +			ctxext.FakeSenderForwardNode(ctx, message.Text(string(t[3]))),
写进上一个循环里，还搁这硬编码呢

2023-05-29 15:00 UTC, Jiang-Red requested changes

2023-05-29 15:00 UTC, Jiang-Red commented on plugin/klala/klala.go
>  	if path, ok = paths.Material[word]; ok {
直接return paths.Material[word]

2023-06-07 14:06 UTC, Jiang-Red commented on go.mod
> +	github.com/lianhong2758/rosm v0.0.0-20230601130055-e16727696467
你觉得你很对？

2023-06-07 14:14 UTC, Jiang-Red requested changes

2023-06-07 14:14 UTC, Jiang-Red commented on go.mod
> +	github.com/lianhong2758/rosm v0.0.0-20230601130055-e16727696467
你觉得你很对？

2023-06-07 14:19 UTC, lianhong2758 commented
呜



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月7日(周三) 晚上10:14
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [FloatTech/ZeroBot-Plugin-Playground] fix cahtgpt无法取消授权的问题 (PR #220)




 
@Jiang-Red requested changes on this pull request.
 
 
In go.mod:
 &gt; @@ -20,6 +20,7 @@ require (  	github.com/golang/freetype v0.0.0-20170609003504-e2365dfdc4a0  	github.com/gorilla/websocket v1.5.0  	github.com/guohuiyuan/go-fyzhq v0.0.0-20220807135412-25c16c843e5a +	github.com/lianhong2758/rosm v0.0.0-20230601130055-e16727696467  
你觉得你很对？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

2023-06-08 08:13 UTC, medicago087 commented
叫 catgpt 得了

2023-06-08 08:51 UTC, lianhong2758 commented
也不是不行的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月8日(周四) 下午4:13
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [FloatTech/ZeroBot-Plugin-Playground] fix cahtgpt无法取消授权的问题 (PR #220)




 
叫 catgpt 得了
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

2023-06-15 12:21 UTC, Jiang-Red approved these changes

2023-06-15 12:43 UTC, merged